[Def]
; Donne un nom à tes simulations
simulation_name = Base

; Seed des simulation pour fixer l'aléatoire
seed = 29081920

; Nombre de simulations utilisées pour l'apprentissage
n_train = 2048

; Nombre de simulations utilisées pour le test
n_test = 500

; Nombre de simulations utilisées pour le fit des MAA
n_fit = 500


[CaseStudy]
; Stabilité de l'air
stability = DN

; Facteur de battement de vent
fb = 3

; Coordonnées de la source (ici Flamanville)
lat = 49.540
lon = -1.883


[Input]
; Liste des entrées à considérer
; (parmi WindSpeed (m/s), HeightRelease (m), Amplitude (%), Rain (mm/h), DepositionVelocity, DepositionVelocityIodine, Scavenging)
variable = WindSpeed, HeightRelease, Amplitude, Rain, DepositionVelocity, DepositionVelocityIodine

; Liste des bornes minimales de chaque entrées
; (dans les unitées précisées précédemment)
min = 0, 0, 10, 0, 5e-4, 1e-5

; Liste des bornes maximales de chaque entrées
; (dans les unitées précisées précédemment)
max = 10, 100, 100, 10, 5e-3, 1e-2

; Liste des transformations
; ("Identity", ou sinon "Log" si besoin de transformer les valeurs avant l'échantillonage)
transform = Identity, Identity, Identity, Identity, Log, Log


[Path]
; Le chemin des données utilisées pour les simulations
input_path = import/

; Le chemin où seront stockées les fichiers de sortie
output_path = export/


[File]
; Nom du fichier source au format CSV situé dans data_path
source_file = PERSAN-1300MWe-EAS-HS-FC-DVxHS-5.csv

; Nom du fichier ref au format PXS situé dans data_path
ref_file = Ref.pxs
